### ISSUE TITLE
The output dimension is different from the input.

### ISSUE THREAD

**Issue by inoue0426** [duct317/scISR#1]
I tried to use this library for the public dataset, but it returned a different dimension.
Do you know why this occurs?

## Dataset

https://www-ncbi-nlm-nih-gov.ezp3.lib.umn.edu/geo/query/acc.cgi?acc=GSE87544
GSE87544_Merged_17samples_14437cells_count.txt.gz

## Environment

```R
R.version
```
                 _                           
    platform       x86_64-pc-linux-gnu         
    arch           x86_64                      
    os             linux-gnu                   
    system         x86_64, linux-gnu           
    status                                     
    major          4                           
    minor          2.0                         
    year           2022                        
    month          04                          
    day            22                          
    svn rev        82229                       
    language       R                           
    version.string R version 4.2.0 (2022-04-22)
    nickname       Vigorous Calisthenics       

```R
packageVersion("scISR")
```
    [1] ‘0.1.1’

## Code and output

```R
library(scISR)
```

```R
data.path <- "../../data/chen/chen_data.csv"

A <- read.csv(
    data.path,
    header = FALSE
)
```

```R
raw = as.matrix(A)
```

```R
dim(raw)
```

14437 ・ 23284

```R
imputed <- scISR(data = raw)
```

```R
dim(imputed)
```

14419 ・ 23284

**Comment by duct317** [comment]
Hi,

Thank you very much for your interest in our package. 

It seems like your input matrix is in form samples * genes. The required input for scISR is matrix of genes * samples. scISR has preprocessing step, so the number of rows/genes would be less in the output (in this case, samples). If you don't want scISR to filter anything, you can set `preprocessing=F` to turn the preprocessing step off.

Let's me know if you have any other problem.

**Comment by inoue0426** [comment]
Hi @duct317 
Thank you for your advice!
I completely misunderstood it. I'll try, thanks!
